name: churchgroupsmanagement
description: A new Flutter project.
license: MIT License
maintainer_email: pixillstudios@gmail.com
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^3.1.1
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  cool_alert: ^2.0.1
  lottie: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  reorderables: ^0.6.0
  percent_indicator: ^4.2.3
  sliding_up_panel: ^2.0.0+1
  grouped_list: ^5.1.2
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#539ef3"
  image: "assets/icons/ic_launcher_foreground.png"
  android_12:
    image: "assets/icons/ic_launcher_foreground.png"
    color: "#539ef3"

# flutter_launcher_icons:
#   android: true
#   adaptive_icon_background: "#539ef3"
#   adaptive_icon_foreground: "assets/images/folder-trans.png"
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/images/folder.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/fonts/Poppins/
    - assets/fonts/Open_Sans/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
    
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-Italic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-LightItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-Medium.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-MediumItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_Condensed-Regular.ttf

    - family: OpenSansSemiCondensed
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-Italic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-LightItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-Medium.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-MediumItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans_SemiCondensed-Regular.ttf
        
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Medium.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-MediumItalic.ttf
